---

name: yamllint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install yamllint
        run: pip3 install yamllint

      - run: yamllint camera-control.yml
